Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace daniel103Website.Models
{
    public class AppUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

ViewModels/AccountViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace daniel103Website.ViewModels
{

    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

}

Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace daniel103Website.Controllers
{
    public class AssignmentController : Controller
    {
        // GET: Assignment
        public ActionResult General()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment1()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment2()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment4()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment5()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment6()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment7()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment9()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }

        public ActionResult Assignment14()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace daniel103Website.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title="daniel carroll";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Title = "daniel carroll";
            return View();
        }
    }
}

Views/Assignment/Assignment1.cshtml
@{
    ViewBag.Title = "daniel carroll";
}
<div class="container">

    <div class="starter-template">
        <h1>hello world
            <br/>
        assignment 1
        </h1>

    </div>

</div><!-- /.container -->

Views/Assignment/Assignment14.cshtml
<script type="text/javascript" src="~/js/flappy/phaser.min.js"></script>
<script type="text/javascript" src="~/js/flappy/loadState.js"></script>
<script type="text/javascript" src="~/js/flappy/menuState.js"></script>
<script type="text/javascript" src="~/js/flappy/gameState.js"></script>
<script type="text/javascript" src="~/js/flappy/init.js"></script>
<div class="container">
    <div class="body">
        <div class="row text-center">
            <div class="page-header">
                <h2>flappy nole!</h2>
            </div>
            <div class="jumbotron">
                <p>
                    this is a game based off a blog tutorial for the Phaser game engine.
                </p>
                <div class="row text-center">
                    <a href="http://blog.lessmilk.com/how-to-make-flappy-bird-in-html5-1/" target="_blank">tutorial - click here</a>
                    <br/>
                    <a href="https://github.com/Hitman666/FlappyBox" target="_blank">github source code - click here</a>
                </div>


            </div>

            <div id="game_div" style="margin: 0 auto; display: table;"> </div>

        </div>

       

    </div>
</div>

Views/Assignment/Assignment2.cshtml
<div class="container">
    <div class="row">
        <br />
        <div class="jumbotron text-center">
            <h1>cop4813 - web development</h1>
            <p>this class focuses on web development using HTML, CSS, and JavaScript </p>

        </div>

        <div class="row text-center">
            <img src="/pictures/HTML5_CSS_JavaScript.png" alt="CodesForWebsite" class="img-responsive center-block" />
        </div>
    </div>
</div>

Views/Assignment/Assignment4.cshtml
<script type="text/javascript" src="http://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript" src="http://code.highcharts.com/modules/exporting.js"></script>


<div class="container">
    <div class="body">
        <div class="row text-center">
            <div class="page-header">
                <h2>logrithmic calculator </h2>

            </div>
            <div class="jumbotron text-left">
                <p>
                    the logrithmic calculator allows you set base values and a constant(w). it will then output the x and y coordinates and
                    graph them so you compare the differnt logs with or without a constant! if you would like to see the code on jsfiddle
                </p>
                <div class="row text-center">
                    <a href="https://jsfiddle.net/danielc103/bcm5k6py/8/" target="_blank"><span class="fa fa-jsfiddle fa-2x"> click here</span></a>
                </div>
            </div>
                
                <div class="col-lg-6">
                   
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">y = log<sub>a</sub>x</h3>
                        </div>
                        <div class="panel-body text-center">

                            <p class="lead">
                                y = log<sub>a</sub>x<br/><br/>
                                <label for="a">Input base value a &nbsp; </label> 
                            <input type="text" id="a" size="5" value="2"/>
                            </p><br />
                            <br /><br />
                           


                            <p class="lead" id="output"> </p>

                            <br /><br />
                        </div>
                    </div>
                </div>

                <div class="col-lg-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">  y = w log<sub>s</sub>x</h3>
                        </div>
                        <div class="panel-body text-center">


                            <p class="lead">
                                y = w log<sub>s</sub>x<br/><br/>
                                <label for="s"> Input base value s &nbsp; </label>
                                <input type="text" id="s" size="5" value="2"/><br/>

                                <label for="w">Input multiplier w &nbsp; &nbsp;</label>
                                    <input type="text" id="w" size="5" value="2"/><br/>
                            </p>
                            <br/>


<p class="lead" id="output2"> </p>

                            <br /><br /><br />
                        </div>
                    </div>


                </div>

            <p class="lead">
                <label for="xmin">X Min &nbsp; &nbsp;</label>
                <input type="text" id="xmin" value="1" size="5" />
                <label for="xmax">&nbsp; X Max &nbsp;</label>
                <input type="text" id="xmax" value="10" size="5"/>
                </p>
                <br /><br />
                <button class="btn btn-info" type="button" id="calculate">calculate!</button>
                <button class="btn btn-info" type="button" id="plot">plot!</button>

                <br /><br />


                <div id="container" style="min-width: 400px; height: 700px; margin: 0 auto"></div>
</div>
        </div>
    </div>





<script type="text/javascript">
    $(window).load(function() {
        
        //global variables
        var a = 0;
        var n = 0;
        var s = 0;
        var w = 0;

        //arrays
        var x = new Array();
        var y = new Array();
        var z = new Array();
        var v = new Array();
        var u = new Array();

        //validate numbers
        function validate() {


            a = Number($('#a').val());
            s = Number($('#s').val());
            w = Number($('#w').val());

            var xmin = Number($('#xmin').val());
            var xmax = Number($('#xmax').val());

            if (a < 0) {
                alert("must have positve number for base a");
                return false;
            }

            if (s < 0) {
                alert("must have positve number for base s");
                return false;
            }

            if (xmin < 1) {
                
                alert("must have positve number for xmin");
                $('#xmin').val('1');
                return false;
            }

            
        }

        //function for getting base of log
        function calculateY(x, y) {
            return Math.log(y) / Math.log(x);
        }

        //function for getting base of log w/ multiplier 
        function calculateZ(x, y, w) {

            return w * (Math.log(y) / Math.log(x));

        }

        //calculate function
        function calculate() {

            a = Number($('#a').val());
            s = Number($('#s').val());
            w = Number($('#w').val());

            var xmin = Number($('#xmin').val());
            var xmax = Number($('#xmax').val());
            var cntr = 0;

           

            var i = 0;
            for (cntr = xmin; cntr <= xmax; cntr++) {

                x[i] = cntr;
                y[i] = calculateY(a, cntr);
                z[i] = calculateZ(s, cntr, w);
                u[i] = [x[i], z[i]];
                v[i] = [x[i], y[i]];
                i++;

            }
            n = i - 1;

        }

        //display the values
        function displayVals() {

            var d = "";
            var e = "";

            for (var i = 0; i <= n; i++) {

                e += " X = " + x[i] + " &nbsp  &nbsp Y = " + z[i].toPrecision(4) + "<br/>";
                d += " X = " + x[i] + " &nbsp  &nbsp Y = " + y[i].toPrecision(4) + "<br/>";

            }
            output.innerHTML = d;
            output2.innerHTML = e;

        }

        //plot the values
        function plotValues() {
            calculate();
            var chart = $('#container').highcharts ({
                chart: {
                   
                    type: 'line'
                   
                },
                title: {
                    text: 'log calc',
                    x: -20 //center
                },
                xAxis: {
                    title: {
                        text: 'X'
                    }
                },
                yAxis: {
                    title: {
                        text: 'Y'
                    }
                },

                plotOptions: {
                    scatter: {
                        marker: {
                            radius: 5,
                            states: {
                                hover: {
                                    enabled: true,
                                    lineColor: 'hex(#0c84e4)'
                                }
                            }
                        },
                        states: {
                            hover: {
                                marker: {
                                    enabled: false
                                }
                            }
                        }
                    }
                },

                series: [{
                    name: 'log',
                    color: '#0c84e4',
                    data: v
                }, {
                    data: u,
                    color: '#198C19',
                    name: 'w log'
                }]
            })
        }





        $('#calculate').click(function () {
            if (validate() == false) {
                return;
            }
            calculate();
            displayVals();
        });

        $('#plot').click(function () {

            if (validate() == false) {
                return;
            }
            calculate();
            plotValues();
            $('#messageModal').modal('toggle');

        });



    })


</script>

Views/Assignment/Assignment5.cshtml
<div class="container">
    <div class="body">
        <div class="row text-center">
            <div class="page-header">
                <h2>spirograph canvas</h2>
            </div>
            <div class="jumbotron">
                <p>
                    the spirograph canvas will create beautiful and amazing random drawings on a canvas. you are able to create multiple at one time, stop them,
                    and also reset the entire canvas. if you would to see the code on jsfiddle
                </p>
                <div class="row text-center">
                    <a href="https://jsfiddle.net/danielc103/ym53dz3h/7/" target="_blank"><span class="fa fa-jsfiddle fa-2x"> click here</span></a>
                </div>
            </div>
            <div class="row text-center">
                <button class="btn btn-info" id="start" onclick="doDrawing();">start drawing!</button>
                <button class="btn btn-info" onclick="stopDrawing();">stop drawing!</button>
                <button class="btn btn-info" onclick="refreshDrawing();">refresh page!</button>
                <br/>
            </div>
            <br/>
            <br/>
            <div class="panel panel-default">
                <canvas id="canvas" width="500" height="500"></canvas>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    /*
hypocycloid from codeprojects
*/

    //global variable for stopping
    var stop = true;

    function doDrawing() {
        //canvas get and context
        var canvas = document.getElementById("canvas");
        var ctx = canvas.getContext("2d");

        //random generators for R = radius of base
        // r = raduis of rolling circle
        var R = Math.random() * 150,
            r = Math.random() * 150,
            s = Math.round(Math.random()),

            //counters
            ti = 1,
            ri = 1,

            //degree position
            t = 0,
            ta = 0,

            //starting x and y coord
            x = 0,
            y = 0,

            //radians for equation
            rad = 0,
            rada = 0;

        //function to get radians for cirlces
        Math.radians = function (degrees) {
            return degrees * Math.PI / 180;
        }

        function draw(R, r, t) {
            ta = t + ti;

            rad = Math.radians(t);
            rada = Math.radians(ta);

            //hypocycloid
            x = (R - r) * Math.cos(rad) + R * Math.cos((R - r) / r * rad) + 250;
            y = (R - r) * Math.sin(rad) - R * Math.sin((R - r) / r * rad) + 250;

            xx = (R - r) * Math.cos(rada) + R * Math.cos((R - r) / r * rada) + 250;
            yy = (R - r) * Math.sin(rada) - R * Math.sin((R - r) / r * rada) + 250;

            //change pretty colors
            newColor();

            //context controls
            ctx.beginPath();
            ctx.moveTo(x, y);
            ctx.lineTo(xx, yy);
            ctx.stroke();

            return;
        }

        //alternate colors for line(stroke)
        function newColor() {
            var color = '#' + Math.floor(Math.random() * 16777215).toString(16);
            ctx.strokeStyle = color;
        }

        //loop for endless fun!
        function loop() {

            //stop if button pressed for stop
            if (stop == false) {
                return;
            }

            draw(R, r, t);
            t += ri;

            //https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
            requestAnimationFrame(loop);
            return;
        }

        requestAnimationFrame(loop);
    }

    //stop the drawing - basically just exits loop and freezes
    function stopDrawing() {
        stop = false;
    }

    //simple refresh entire page to start over again - quick and painless.
    function refreshDrawing() {
        location.reload();
    }

</script>

Views/Assignment/General.cshtml
<div class="container">
    <div class="row">
        <br/>
        <div class="jumbotron text-center">
            <h1>cop4813 - web development</h1>
            <p>this class focuses on web development using HTML, CSS, and JavaScript </p>

        </div>

        <div class="row text-center">
            <img src="/pictures/HTML5_CSS_JavaScript.png"/>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
<div class="container">

    <div class="body">
        <div class="row">
            <br />
            <div class="page-header">
                <img src="/pictures/css3.png" alt="cssImage" class=" img-responsive" />
                <h1>welcome to my website for cop4813!</h1>
            </div>

            <blockquote>
                <p> “If debugging is the process of removing software bugs, then programming must be the process of putting them in.”</p>
                <small>Edsger Dijkstra <cite title="Source Title">Dutch computer scientist</cite></small>
            </blockquote>

        </div>

        <br />
        <br />
        <br />
    </div>



    <div class="jumbotron">
        <h2>homework for cop4813</h2>
        <p>i'll leave some links here for the homework with a brief description. this will be updated throughout the semester. hope you enjoy the website.</p>
        <div class="text-center">
            <a class="twitter-timeline" href="https://twitter.com/engadget" data-widget-id="660959993789882368">Tweets by engadget</a>
        </div>
        <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + "://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs");</script>
    </div>
    <div class="col-lg-4">

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 1</h3>
            </div>
            <div class="panel-body">
                put a simple "hello world" web site on the internet at a registered domain
                <br />
                <br />
                <br />
            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 4</h3>
            </div>
            <div class="panel-body">
                Create a plotting calculator - real inline plotting. This will be your first time using add-in libraries that are available in JavaScript.
                There are many - in this case you will use jQuery and Highcharts. <a href="@Url.Action("Assignment4", "Assignment")">click here</a>
                <br />
                <br />

            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 7</h3>
            </div>
            <div class="panel-body">
                In this assignment you will be creating a drag and drop based assignment. <a href="@Url.Action("Assignment7", "Assignment")">click here</a>
                <br />
                <br />
                <br />

            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 7</h3>
            </div>
            <div class="panel-body">
                In this assignment you will be designing and implementing a JavaScript game. <a href="@Url.Action("Assignment14", "Assignment")">click here</a>
                <br />
                <br />
                <br />

            </div>
        </div>


    </div>

    <div class="col-lg-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 2</h3>
            </div>
            <div class="panel-body">
                create a fully functional page at your new web site to support the class and all the upcoming assignments.
                you will need to have a menu on your page, so start brushing up on CSS and JavaScript. <a href="@Url.Action("Assignment1", "Assignment")">click here</a>
            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 5</h3>
            </div>
            <div class="panel-body">
                Starting with the HTML 5 canvas by creating a Spirograph. The Canvas is a wonderful thing, a drawing surface that is pretty easy to use.
                <a href="@Url.Action("Assignment5", "Assignment")">click here</a>
                <br />
                <br />
                <br />

            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 8</h3>
            </div>
            <div class="panel-body">
                Create Use Case Scenarios that are unique to your project and document as a use case scenario.
                Note you do not need to produce Use Case for common functions like login or creating an accoun <a href="~/PDF/Assignment8.pdf">click here</a>


            </div>
        </div>

    </div>

    <div class="col-lg-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 3</h3>
            </div>
            <div class="panel-body">
                create a fully functional form with JavaScript validation. <a href="@Url.Action("Contact", "Home")">click here</a>
                <br />
                <br />
                <br />
            </div>

        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 6</h3>
            </div>
            <div class="panel-body">
                You are going to work with some existing XML languages, creating 3 pages.
                You will use three languages; Math Markup Language (MathML), Scalable Vector Graphics (SVG) , and Keyhole Markup Language (KML).
                <a href="@Url.Action("Assignment6", "Assignment")">click here</a>

                <br />


            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">assignment 9</h3>
            </div>
            <div class="panel-body">
                In this assignment you will animate an object on a canvas. You may animate any type of object (image or an object drawn on the screen).
                <a href="@Url.Action("Assignment9", "Assignment")">click here</a>
                <br />
                <br />

            </div>
        </div>

    </div>

</div><!-- /.container -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("../../css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("../../css/starter-template.css")" rel="stylesheet">


    <!--Font Awesome-->
    <link href="@Url.Content("../../css/font-awesome.css")" rel="stylesheet"/>


    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>



    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">@ViewBag.Title</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-right nav navbar-nav">
                <li><a href="@Url.Action("Index", "Home")"><span class="fa fa-home"></span> home</a></li>
                <li><a href="@Url.Action("Contact", "Home")" class="elements"><span class="fa fa-envelope"></span> contact</a></li>
                <li class="dropdown">
                    <a href="#school" class="dropdown-toggle" data-toggle="dropdown" role="button"><span class="fa fa-university"></span> school<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="http://www.fsu.edu" target="_blank"><span class="fa fa-university fa-fw"></span>&nbsp; florida state university</a></li>
                        <li class="divider"></li>
                        <li><a href="http://daytonastate.edu/" target="_blank"><span class="fa fa-university fa-fw"></span>&nbsp; daytona state college</a></li>
                        <li class="divider"></li>
                        <li><a href="@Url.Action("Assignment1", "Assignment")">assignment 1</a></li>
                        <li><a href="@Url.Action("Assignment2", "Assignment")">assignment 2</a></li>
                        <li><a href="@Url.Action("Contact", "Home")">assignment 3</a></li>
                        <li><a href="@Url.Action("Assignment4", "Assignment")">assignment 4</a></li>
                        <li><a href="@Url.Action("Assignment5", "Assignment")">assignment 5</a></li>
                        <li><a href="@Url.Action("Assignment6", "Assignment")">assignment 6</a></li>
                        <li><a href="@Url.Action("Assignment7", "Assignment")">assignment 7</a></li>
                        <li><a href="~/PDF/Assignment8.pdf">assignment 8</a></li>
                        <li><a href="@Url.Action("Assignment9", "Assignment")">assignment 9</a></li>
                        <li><a href="@Url.Action("Assignment14", "Assignment")">assignment 14</a></li>

                    </ul>

                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-comments"></span> social<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="https://www.linkedin.com/in/danielccarroll" target="_blank"><span class="fa fa-linkedin fa-fw"></span> LinkedIn</a></li>
                        <li><a href="https://www.google.com/+DanielCarroll" target="_blank"><span class="fa fa-google-plus fa-fw"></span> Google+</a></li>
                        <li><a href="https://github.com/danielc103" target="_blank"><span class="fa fa-github fa-fw"></span> GitHub</a></li>
                        <li><a href="https://bitbucket.org/danc103" target="_blank"><span class="fa fa-bitbucket fa-fw"></span> BitBucket</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-chrome"></span> favorite sites<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="https://www.stackoverflow.com" target="_blank"><span class="fa fa-stack-overflow fa-fw"></span> stackoverflow</a></li>
                        <li><a href="https://www.msdn.com" target="_blank"><span class="fa fa-windows fa-fw"></span> msdn</a></li>
                    </ul>
                </li>

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
@RenderBody()

<br/>
<br/>

<footer>
    <div class="container">
        <div class="row">

            <ul class="list-inline">
                <li class="pull-right"><a href="#top"><span class="fa fa-angle-up"></span> back to top of page</a></li>
                <li><a href="@Url.Action("Index", "Home")"><span class="fa fa-home"></span> home</a></li>
                <li><a href="#" data-toggle="modal" data-target="#contactModal"><span class="fa fa-envelope"></span> quick contact</a></li>

                <li></li>
            </ul>

        </div>
    </div>
    <br/>

    <div class="container">
        <div class="row">
            <p class="pull-left"><span class="fa fa-copyright"></span>Made by Daniel Carroll
            </p>
        </div>
    </div>
</footer>



<script type="text/javascript" src="@Url.Content("~/js/bootstrap.js")"></script>

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- ad_1 -->
    <div class="text-center">
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-2299972602700648"
             data-ad-slot="4501720016"
             data-ad-format="auto"></ins>
    </div>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</body>


</html>